//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogDataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogTopic
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public int CategoryID { get; set; }
    
        public virtual BlogCategory BlogCategory { get; set; }
        public virtual User User { get; set; }
    }
}
